UPDATE profiles SET username = 'رضا شاكر رضا' WHERE job_number = '103142056' AND governorate = 'babil';
UPDATE profiles SET username = 'مؤيد رمضان نعيثل' WHERE job_number = '103142465' AND governorate = 'babil';
UPDATE profiles SET username = 'قاسم مهدي يحيى' WHERE job_number = '103142902' AND governorate = 'babil';
UPDATE profiles SET username = 'كريم نعمة عبد' WHERE job_number = '103142605' AND governorate = 'babil';
UPDATE profiles SET username = 'رجاء صادق حسين' WHERE job_number = '103143541' AND governorate = 'babil';
UPDATE profiles SET username = 'رباب مسلم فاضل' WHERE job_number = '103143848' AND governorate = 'babil';
UPDATE profiles SET username = 'حسب الله خريبط عبود' WHERE job_number = '103220659' AND governorate = 'babil';
UPDATE profiles SET username = 'عدنان هادي حسن' WHERE job_number = '103140568' AND governorate = 'babil';
UPDATE profiles SET username = 'ايمان تاية داود' WHERE job_number = '103139681' AND governorate = 'babil';
UPDATE profiles SET username = 'ولاء أياد طه' WHERE job_number = '103140526' AND governorate = 'babil';
UPDATE profiles SET username = 'سهاد قاسم غني' WHERE job_number = '103140609' AND governorate = 'babil';
UPDATE profiles SET username = 'اخلاص قنبر ايوز' WHERE job_number = '103141532' AND governorate = 'babil';
UPDATE profiles SET username = 'نبا سعدون سكر' WHERE job_number = '103142775' AND governorate = 'babil';
UPDATE profiles SET username = 'ميثم صلاح عبد الأمير' WHERE job_number = '103139483' AND governorate = 'babil';
UPDATE profiles SET username = 'مديحة حميد عبد علي' WHERE job_number = '103139636' AND governorate = 'babil';
UPDATE profiles SET username = 'ناهدة فاضل موسى' WHERE job_number = '103139850' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد والي عطوان' WHERE job_number = '103141206' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب وهاب مجيد' WHERE job_number = '103140696' AND governorate = 'babil';
UPDATE profiles SET username = 'خلودة كاظم محيميد' WHERE job_number = '103142069' AND governorate = 'babil';
UPDATE profiles SET username = 'مها عبد اللطيف عيدان' WHERE job_number = '103139470' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس قسام زيدان' WHERE job_number = '103140571' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر عيدان عيسى' WHERE job_number = '103141350' AND governorate = 'babil';
UPDATE profiles SET username = 'فاضل حمد كاظم' WHERE job_number = '103145518' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن حمزة عبد الله' WHERE job_number = '103222866' AND governorate = 'babil';
UPDATE profiles SET username = 'عامر عبد الحمزة محمد' WHERE job_number = '103139566' AND governorate = 'babil';
UPDATE profiles SET username = 'فارس وهيب عبيد' WHERE job_number = '103141503' AND governorate = 'babil';
UPDATE profiles SET username = 'خالد سعدون حميد' WHERE job_number = '103143781' AND governorate = 'babil';
UPDATE profiles SET username = 'منيرة كاظم محسن' WHERE job_number = '103141727' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر جبار كريم' WHERE job_number = '103139959' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عسكر عمران' WHERE job_number = '103141079' AND governorate = 'babil';
UPDATE profiles SET username = 'تغريد علي عباس' WHERE job_number = '103142957' AND governorate = 'babil';
UPDATE profiles SET username = 'سمير عدنان موسى' WHERE job_number = '103144502' AND governorate = 'babil';
UPDATE profiles SET username = 'اديب سالم ربيط' WHERE job_number = '103139975' AND governorate = 'babil';
UPDATE profiles SET username = 'وجدان خضير حمد' WHERE job_number = '103142014' AND governorate = 'babil';
UPDATE profiles SET username = 'عذراء حمزة عبيد' WHERE job_number = '103141475' AND governorate = 'babil';
UPDATE profiles SET username = 'نوال حسين عليوي' WHERE job_number = '103139751' AND governorate = 'babil';
UPDATE profiles SET username = 'حنان هادي سعيد' WHERE job_number = '103139553' AND governorate = 'babil';
UPDATE profiles SET username = 'مرتضى محمود ناجي' WHERE job_number = '103207467' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس كتاب رباط' WHERE job_number = '103142759' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر علي حسون' WHERE job_number = '103142171' AND governorate = 'babil';
UPDATE profiles SET username = 'ختام جواد كاظم' WHERE job_number = '103139821' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد عبد عبيس' WHERE job_number = '103142762' AND governorate = 'babil';
UPDATE profiles SET username = 'صادق جبار عبادة' WHERE job_number = '103142379' AND governorate = 'babil';
UPDATE profiles SET username = 'ميادة عدنان محمد' WHERE job_number = '103146623' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب محمد ناجي' WHERE job_number = '103140542' AND governorate = 'babil';
UPDATE profiles SET username = 'ظافر نوري جواد' WHERE job_number = '103141615' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد عبد اللطيف عبيد' WHERE job_number = '103141404' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس عبد الزهرة حسين' WHERE job_number = '103141011' AND governorate = 'babil';
UPDATE profiles SET username = 'عولية جواد كاظم' WHERE job_number = '103140638' AND governorate = 'babil';
UPDATE profiles SET username = 'خالد عبود علوان' WHERE job_number = '102514649' AND governorate = 'babil';
UPDATE profiles SET username = 'سامر علي حسين' WHERE job_number = '102254480' AND governorate = 'babil';
UPDATE profiles SET username = 'ثامر عبدالجبار عبدالعباس' WHERE job_number = '102254419' AND governorate = 'babil';
UPDATE profiles SET username = 'سعد يحيى خضير' WHERE job_number = '103222936' AND governorate = 'babil';
UPDATE profiles SET username = 'رائدة عبد الحسين كاظم' WHERE job_number = '103140597' AND governorate = 'babil';
UPDATE profiles SET username = 'عامر حسين كاظم' WHERE job_number = '103141235' AND governorate = 'babil';
UPDATE profiles SET username = 'خلود حمزة عبد الله' WHERE job_number = '103139917' AND governorate = 'babil';
UPDATE profiles SET username = 'عايد طالب حسون' WHERE job_number = '103141334' AND governorate = 'babil';
UPDATE profiles SET username = 'هادي عبيد حمود' WHERE job_number = '103139818' AND governorate = 'babil';
UPDATE profiles SET username = 'سعاد حامد جاسم' WHERE job_number = '103139834' AND governorate = 'babil';
UPDATE profiles SET username = 'عبد الامير محمد علي' WHERE job_number = '103139524' AND governorate = 'babil';
UPDATE profiles SET username = 'شيماء وهيب صبار' WHERE job_number = '103139706' AND governorate = 'babil';
UPDATE profiles SET username = 'ايناس صادق محسن' WHERE job_number = '103144445' AND governorate = 'babil';
UPDATE profiles SET username = 'خمائل غازي حسين' WHERE job_number = '103141938' AND governorate = 'babil';
UPDATE profiles SET username = 'تحسين علي عبد الرضا' WHERE job_number = '103142098' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد حبيب جاسم' WHERE job_number = '103142085' AND governorate = 'babil';
UPDATE profiles SET username = 'صفاء كامل عبيد' WHERE job_number = '103143158' AND governorate = 'babil';
UPDATE profiles SET username = 'ابتسام محمد سلمان' WHERE job_number = '103143398' AND governorate = 'babil';
UPDATE profiles SET username = 'سهاد سليم عباس' WHERE job_number = '103139272' AND governorate = 'babil';
UPDATE profiles SET username = 'رنا جبار شعلان' WHERE job_number = '103143385' AND governorate = 'babil';
UPDATE profiles SET username = 'سهاد غانم عباس' WHERE job_number = '103141318' AND governorate = 'babil';
UPDATE profiles SET username = 'رضا حمزة عبادي' WHERE job_number = '103139173' AND governorate = 'babil';
UPDATE profiles SET username = 'لقاء فاهم محيي' WHERE job_number = '103141181' AND governorate = 'babil';
UPDATE profiles SET username = 'رغد عباس نوري' WHERE job_number = '103207230' AND governorate = 'babil';
UPDATE profiles SET username = 'عماد عبد الامير عبد الله' WHERE job_number = '103143822' AND governorate = 'babil';
UPDATE profiles SET username = 'تماضر يحيى مهدي' WHERE job_number = '103139313' AND governorate = 'babil';
UPDATE profiles SET username = 'رضية علوان عودة' WHERE job_number = '103142225' AND governorate = 'babil';
UPDATE profiles SET username = 'رويدة فاضل عبد' WHERE job_number = '103142072' AND governorate = 'babil';
UPDATE profiles SET username = 'هدى غازي هادي' WHERE job_number = '103141996' AND governorate = 'babil';
UPDATE profiles SET username = 'علي بدر حمزة' WHERE job_number = '103142704' AND governorate = 'babil';
UPDATE profiles SET username = 'بسام خالد جاسم' WHERE job_number = '103141628' AND governorate = 'babil';
UPDATE profiles SET username = 'ايمان علاوي جونه' WHERE job_number = '103143570' AND governorate = 'babil';
UPDATE profiles SET username = 'انتصار محمد خليفة' WHERE job_number = '103139777' AND governorate = 'babil';
UPDATE profiles SET username = 'داليا علي حسين' WHERE job_number = '103141149' AND governorate = 'babil';
UPDATE profiles SET username = 'وفاء كاظم عباس' WHERE job_number = '103139764' AND governorate = 'babil';
UPDATE profiles SET username = 'سوسن غانم عبد العباس' WHERE job_number = '103142184' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد فضيل شناوة' WHERE job_number = '103141194' AND governorate = 'babil';
UPDATE profiles SET username = 'مائدة ياسر علي' WHERE job_number = '103196628' AND governorate = 'babil';
UPDATE profiles SET username = 'اسراء حمود حمزة' WHERE job_number = '103140386' AND governorate = 'babil';
UPDATE profiles SET username = 'سهاد عبد الوهاب محمد' WHERE job_number = '103139991' AND governorate = 'babil';
UPDATE profiles SET username = 'سمر حسين هاشم' WHERE job_number = '103140430' AND governorate = 'babil';
UPDATE profiles SET username = 'احسان صادق عبد الحسين' WHERE job_number = '103140485' AND governorate = 'babil';
UPDATE profiles SET username = 'ضمياء كاظم سماوي' WHERE job_number = '103140724' AND governorate = 'babil';
UPDATE profiles SET username = 'علي رجا عنيد' WHERE job_number = '103142366' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد وهيب هاشم' WHERE job_number = '103140964' AND governorate = 'babil';
UPDATE profiles SET username = 'سوزان محمد علي' WHERE job_number = '103139537' AND governorate = 'babil';
UPDATE profiles SET username = 'عقيل حامد عبيس' WHERE job_number = '102514665' AND governorate = 'babil';
UPDATE profiles SET username = 'سارة فاضل جابر' WHERE job_number = '102514681' AND governorate = 'babil';
UPDATE profiles SET username = 'دنيا داود سلمان' WHERE job_number = '103139579' AND governorate = 'babil';
UPDATE profiles SET username = 'اخلاص عيسى جاسم' WHERE job_number = '103139678' AND governorate = 'babil';
UPDATE profiles SET username = 'عايد علي مهدي' WHERE job_number = '103140584' AND governorate = 'babil';
UPDATE profiles SET username = 'مخلص توفيق عبد الأمير' WHERE job_number = '103141024' AND governorate = 'babil';
UPDATE profiles SET username = 'ختام فضيل شناوة' WHERE job_number = '103142209' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين خضير عبيس' WHERE job_number = '103145659' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين عبد علي عاكول' WHERE job_number = '103141095' AND governorate = 'babil';
UPDATE profiles SET username = 'سندس اسماعيل حميد' WHERE job_number = '103140906' AND governorate = 'babil';
UPDATE profiles SET username = 'امال منعم موسى' WHERE job_number = '103140427' AND governorate = 'babil';
UPDATE profiles SET username = 'اثير فاضل عباس' WHERE job_number = '103139946' AND governorate = 'babil';
UPDATE profiles SET username = 'جواد كاظم موسى' WHERE job_number = '103139892' AND governorate = 'babil';
UPDATE profiles SET username = 'صباح زغير حميد' WHERE job_number = '103141730' AND governorate = 'babil';
UPDATE profiles SET username = 'وسام عباس حمزة' WHERE job_number = '103141417' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر علي حسين' WHERE job_number = '103140935' AND governorate = 'babil';
UPDATE profiles SET username = 'فائز عباس حسن' WHERE job_number = '103141053' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر حاتم شردغلي' WHERE job_number = '102514652' AND governorate = 'babil';
UPDATE profiles SET username = 'مسار محي موسى' WHERE job_number = '103141277' AND governorate = 'babil';
UPDATE profiles SET username = 'شيماء عبد الرزاق عبد الشهيد' WHERE job_number = '103140894' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن جواد كاظم' WHERE job_number = '102514623' AND governorate = 'babil';
UPDATE profiles SET username = 'ايمان حسن عليوي' WHERE job_number = '103141178' AND governorate = 'babil';
UPDATE profiles SET username = 'عبير مالك عبيد' WHERE job_number = '103139508' AND governorate = 'babil';
UPDATE profiles SET username = 'شاكر حسن مطر' WHERE job_number = '103140357' AND governorate = 'babil';
UPDATE profiles SET username = 'علي حسين بربش' WHERE job_number = '103139368' AND governorate = 'babil';
UPDATE profiles SET username = 'فرح علي حسين' WHERE job_number = '103139397' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب عبد الله عمران' WHERE job_number = '103140539' AND governorate = 'babil';
UPDATE profiles SET username = 'قايد حمزة حسون' WHERE job_number = '103142973' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد ماجد قاسم' WHERE job_number = '103141743' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد كامل كريم' WHERE job_number = '103142197' AND governorate = 'babil';
UPDATE profiles SET username = 'قاسم محمد عبد الرضا' WHERE job_number = '103142519' AND governorate = 'babil';
UPDATE profiles SET username = 'جاسم طاهر جاسم' WHERE job_number = '103142577' AND governorate = 'babil';
UPDATE profiles SET username = 'فراس عبد الرحيم راضي' WHERE job_number = '103140865' AND governorate = 'babil';
UPDATE profiles SET username = 'قاسم طراد جودة' WHERE job_number = '103143864' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس هاشم جاسم' WHERE job_number = '103142241' AND governorate = 'babil';
UPDATE profiles SET username = 'رفاه عبود حسن' WHERE job_number = '103141264' AND governorate = 'babil';
UPDATE profiles SET username = 'اسيل عباس جابر' WHERE job_number = '103142634' AND governorate = 'babil';
UPDATE profiles SET username = 'ناظم كاظم طالب' WHERE job_number = '103143749' AND governorate = 'babil';
UPDATE profiles SET username = 'هيثم مالك عبيد' WHERE job_number = '103139962' AND governorate = 'babil';
UPDATE profiles SET username = 'عطور عبود منجي' WHERE job_number = '103139610' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد مهدي غزوان' WHERE job_number = '103141516' AND governorate = 'babil';
UPDATE profiles SET username = 'قصي عبد الوهاب محمدعلي' WHERE job_number = '103141462' AND governorate = 'babil';
UPDATE profiles SET username = 'اسعد عادل عبيد' WHERE job_number = '103139582' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين حامد عباس' WHERE job_number = '103139384' AND governorate = 'babil';
UPDATE profiles SET username = 'شامل معز راضي' WHERE job_number = '103139722' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر صادق صالح' WHERE job_number = '106371459' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين توفيق حلبوص' WHERE job_number = '103139467' AND governorate = 'babil';
UPDATE profiles SET username = 'صلاح مهدي حمود' WHERE job_number = '103139694' AND governorate = 'babil';
UPDATE profiles SET username = 'امير مؤيد حسين' WHERE job_number = '103133906' AND governorate = 'babil';
UPDATE profiles SET username = 'هاني عبيد خضير' WHERE job_number = '103145464' AND governorate = 'babil';
UPDATE profiles SET username = 'صبا رزاق هادي' WHERE job_number = '103139904' AND governorate = 'babil';
UPDATE profiles SET username = 'فراس عباس كاظم' WHERE job_number = '103140779' AND governorate = 'babil';
UPDATE profiles SET username = 'عصام هادي مهدي' WHERE job_number = '103139735' AND governorate = 'babil';
UPDATE profiles SET username = 'ثامر فهد عبد نور' WHERE job_number = '103141756' AND governorate = 'babil';
UPDATE profiles SET username = 'حميد مسلم كريم' WHERE job_number = '103141392' AND governorate = 'babil';
UPDATE profiles SET username = 'وضاح عبدالهادي عباس' WHERE job_number = '102514719' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر عبيد راضي' WHERE job_number = '106371363' AND governorate = 'babil';
UPDATE profiles SET username = 'محسن فيصل جبر' WHERE job_number = '103140443' AND governorate = 'babil';
UPDATE profiles SET username = 'عدنان مطشر حسن' WHERE job_number = '103142928' AND governorate = 'babil';
UPDATE profiles SET username = 'شيماء صالح مهدي' WHERE job_number = '103143947' AND governorate = 'babil';
UPDATE profiles SET username = 'اياد قحطان محيسن' WHERE job_number = '103143062' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب رزاق علي' WHERE job_number = '103140498' AND governorate = 'babil';
UPDATE profiles SET username = 'رائد عبد الكاظم عطية' WHERE job_number = '103142791' AND governorate = 'babil';
UPDATE profiles SET username = 'امجد حميد محمد' WHERE job_number = '103141590' AND governorate = 'babil';
UPDATE profiles SET username = 'ميثم مكي جاسم' WHERE job_number = '103139876' AND governorate = 'babil';
UPDATE profiles SET username = 'سهيلة جابر حمزة' WHERE job_number = '103210324' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين صالح هادي' WHERE job_number = '103141082' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين شاهي عبود' WHERE job_number = '103142324' AND governorate = 'babil';
UPDATE profiles SET username = 'وميض عبد الرزاق حمود' WHERE job_number = '103143442' AND governorate = 'babil';
UPDATE profiles SET username = 'صفاء خشان حسين' WHERE job_number = '103140807' AND governorate = 'babil';
UPDATE profiles SET username = 'عقيل محمد هاشم' WHERE job_number = '103142915' AND governorate = 'babil';
UPDATE profiles SET username = 'مياسة قاسم غني' WHERE job_number = '103141008' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر عبد عون محمد' WHERE job_number = '103142803' AND governorate = 'babil';
UPDATE profiles SET username = 'كاظم حبيب عناد' WHERE job_number = '103139227' AND governorate = 'babil';
UPDATE profiles SET username = 'فراس طة إبراهيم' WHERE job_number = '103143017' AND governorate = 'babil';
UPDATE profiles SET username = 'مشتاق طالب حميد' WHERE job_number = '103140922' AND governorate = 'babil';
UPDATE profiles SET username = 'عبد الرحمن حوران  مطر' WHERE job_number = '103142506' AND governorate = 'babil';
UPDATE profiles SET username = 'ناطق محمد ذياب' WHERE job_number = '103140977' AND governorate = 'babil';
UPDATE profiles SET username = 'ماجد عبد علي نعمة' WHERE job_number = '103144698' AND governorate = 'babil';
UPDATE profiles SET username = 'عبدالوهاب عبدالرزاق بليبص' WHERE job_number = '103140034' AND governorate = 'babil';
UPDATE profiles SET username = 'سلوان عباس قحط' WHERE job_number = '103142960' AND governorate = 'babil';
UPDATE profiles SET username = 'التفات عبد الكاظم شكر' WHERE job_number = '103139298' AND governorate = 'babil';
UPDATE profiles SET username = 'زهرة عبد الامير ماهر' WHERE job_number = '103142043' AND governorate = 'babil';
UPDATE profiles SET username = 'عذراء غازي شهيد' WHERE job_number = '103143963' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد شاكر عبد' WHERE job_number = '103220662' AND governorate = 'babil';
UPDATE profiles SET username = 'حامد هاشم محمد علي' WHERE job_number = '103220688' AND governorate = 'babil';
UPDATE profiles SET username = 'حمزية عبيس حداد' WHERE job_number = '103143075' AND governorate = 'babil';
UPDATE profiles SET username = 'رقية حاتم سربوت' WHERE job_number = '103141842' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر علي لعيبي' WHERE job_number = '103139454' AND governorate = 'babil';
UPDATE profiles SET username = 'نجلاء هادي عبيد' WHERE job_number = '103139214' AND governorate = 'babil';
UPDATE profiles SET username = 'سوسن رؤوف كاظم' WHERE job_number = '103143400' AND governorate = 'babil';
UPDATE profiles SET username = 'علي حسين علوان' WHERE job_number = '103143611' AND governorate = 'babil';
UPDATE profiles SET username = 'سناء عبيد حسين' WHERE job_number = '103143596' AND governorate = 'babil';
UPDATE profiles SET username = 'ايمان محمد حسن' WHERE job_number = '103140683' AND governorate = 'babil';
UPDATE profiles SET username = 'نور عبد الأمير عايز' WHERE job_number = '103139441' AND governorate = 'babil';
UPDATE profiles SET username = 'لطيف ناجي عبيد' WHERE job_number = '103142944' AND governorate = 'babil';
UPDATE profiles SET username = 'محسن فلاح عمران' WHERE job_number = '103140641' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين محمد علوان' WHERE job_number = '103139748' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد عبد زيد عباس' WHERE job_number = '103141769' AND governorate = 'babil';
UPDATE profiles SET username = 'عبير حسين جاسم' WHERE job_number = '103139607' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس فاضل حسن' WHERE job_number = '103143707' AND governorate = 'babil';
UPDATE profiles SET username = 'ماجد خضير عبيس' WHERE job_number = '103141321' AND governorate = 'babil';
UPDATE profiles SET username = 'بشرى زويد حسين' WHERE job_number = '103139230' AND governorate = 'babil';
UPDATE profiles SET username = 'ليالي غني مهدي' WHERE job_number = '103144601' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد وهيب جاسم' WHERE job_number = '103141066' AND governorate = 'babil';
UPDATE profiles SET username = 'جاسم محمد حمزة' WHERE job_number = '103145633' AND governorate = 'babil';
UPDATE profiles SET username = 'سحر عبد العباس اسود' WHERE job_number = '103140782' AND governorate = 'babil';
UPDATE profiles SET username = 'صالح حسن ناصر' WHERE job_number = '103142100' AND governorate = 'babil';
UPDATE profiles SET username = 'قاسم تايه داود' WHERE job_number = '103144135' AND governorate = 'babil';
UPDATE profiles SET username = 'ايمان حمزة عودة' WHERE job_number = '103139243' AND governorate = 'babil';
UPDATE profiles SET username = 'امنة عبود عبد الرضا' WHERE job_number = '103141813' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد جاسم موسى' WHERE job_number = '103140948' AND governorate = 'babil';
UPDATE profiles SET username = 'نجود مجيد حسين' WHERE job_number = '103142931' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس فاضل حمزة' WHERE job_number = '103142717' AND governorate = 'babil';
UPDATE profiles SET username = 'بشار اكرم كاظم' WHERE job_number = '103145620' AND governorate = 'babil';
UPDATE profiles SET username = 'منال سهيل مصحب' WHERE job_number = '103144007' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد جواد كاظم' WHERE job_number = '103140836' AND governorate = 'babil';
UPDATE profiles SET username = 'ميثم عبد الكاظم عبدالحمزة' WHERE job_number = '103141347' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب عبد الرزاق كاظم' WHERE job_number = '103142689' AND governorate = 'babil';
UPDATE profiles SET username = 'فارس نور حسن' WHERE job_number = '103140708' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر حسن عبد العباس' WHERE job_number = '103139780' AND governorate = 'babil';
UPDATE profiles SET username = 'علاء محسن جياد' WHERE job_number = '103143116' AND governorate = 'babil';
UPDATE profiles SET username = 'مشتاق فوزي حلبوص' WHERE job_number = '103142238' AND governorate = 'babil';
UPDATE profiles SET username = 'ندى جواد إبراهيم' WHERE job_number = '103140472' AND governorate = 'babil';
UPDATE profiles SET username = 'علي محمد علي سلمان' WHERE job_number = '103145097' AND governorate = 'babil';
UPDATE profiles SET username = 'عقيل جاسم محمد' WHERE job_number = '102515192' AND governorate = 'babil';
UPDATE profiles SET username = 'رنا ليث عبد الستار' WHERE job_number = '103139438' AND governorate = 'babil';
UPDATE profiles SET username = 'فراس فاضل محمد' WHERE job_number = '103141574' AND governorate = 'babil';
UPDATE profiles SET username = 'شادية عسرود محمد' WHERE job_number = '103142395' AND governorate = 'babil';
UPDATE profiles SET username = 'سالم زبير عبيس' WHERE job_number = '103143215' AND governorate = 'babil';
UPDATE profiles SET username = 'ماهر شاكر نعمة' WHERE job_number = '103141855' AND governorate = 'babil';
UPDATE profiles SET username = 'خالد عبد الاله عبد جواد' WHERE job_number = '103142522' AND governorate = 'babil';
UPDATE profiles SET username = 'رافت جواد ناجي' WHERE job_number = '103140667' AND governorate = 'babil';
UPDATE profiles SET username = 'حسام مجيد عبد علي' WHERE job_number = '103142548' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد محمد عبد ظفير' WHERE job_number = '103210197' AND governorate = 'babil';
UPDATE profiles SET username = 'ثامر كاظم مظلوم' WHERE job_number = '103144825' AND governorate = 'babil';
UPDATE profiles SET username = 'سرمد علي مجيد' WHERE job_number = '103141376' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد عبد الأمير عليوي' WHERE job_number = '103140360' AND governorate = 'babil';
UPDATE profiles SET username = 'شاكر حاكم عبيس' WHERE job_number = '103143059' AND governorate = 'babil';
UPDATE profiles SET username = 'جاسم محمد حسين' WHERE job_number = '103142663' AND governorate = 'babil';
UPDATE profiles SET username = 'زاهد محسن عبيد' WHERE job_number = '103142647' AND governorate = 'babil';
UPDATE profiles SET username = 'صالح مهدي نجم' WHERE job_number = '103142986' AND governorate = 'babil';
UPDATE profiles SET username = 'باسم حمد عباس' WHERE job_number = '103142423' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد عبد الحسين حميدي' WHERE job_number = '103141446' AND governorate = 'babil';
UPDATE profiles SET username = 'فاتن سليم حمزة' WHERE job_number = '103139355' AND governorate = 'babil';
UPDATE profiles SET username = 'باسم هادي كاظم' WHERE job_number = '103139793' AND governorate = 'babil';
UPDATE profiles SET username = 'سمهر صادق حمد' WHERE job_number = '103139511' AND governorate = 'babil';
UPDATE profiles SET username = 'فاروق مرزة حسين' WHERE job_number = '103142212' AND governorate = 'babil';
UPDATE profiles SET username = 'زعال شخير كزار' WHERE job_number = '103143187' AND governorate = 'babil';
UPDATE profiles SET username = 'صلاح هادي ساهي' WHERE job_number = '103141699' AND governorate = 'babil';
UPDATE profiles SET username = 'اسعد عباس حسون' WHERE job_number = '103142580' AND governorate = 'babil';
UPDATE profiles SET username = 'بهاء ستار عبد الأمير' WHERE job_number = '103143356' AND governorate = 'babil';
UPDATE profiles SET username = 'ماجد عباس حسن' WHERE job_number = '103140823' AND governorate = 'babil';
UPDATE profiles SET username = 'انور فؤاد ماجد' WHERE job_number = '103145419' AND governorate = 'babil';
UPDATE profiles SET username = 'سعد ابراهيم جبر' WHERE job_number = '103142296' AND governorate = 'babil';
UPDATE profiles SET username = 'غيث جميل حميد' WHERE job_number = '103143369' AND governorate = 'babil';
UPDATE profiles SET username = 'ايثم حمزة غلفص' WHERE job_number = '103142311' AND governorate = 'babil';
UPDATE profiles SET username = 'فاطمة محمود جاسم' WHERE job_number = '103141839' AND governorate = 'babil';
UPDATE profiles SET username = 'عمار جواد كاظم' WHERE job_number = '103141363' AND governorate = 'babil';
UPDATE profiles SET username = 'ثائر عبيد اسود' WHERE job_number = '103142551' AND governorate = 'babil';
UPDATE profiles SET username = 'علاء عدنان جاسم' WHERE job_number = '103143273' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر احمد جاسم' WHERE job_number = '103142436' AND governorate = 'babil';
UPDATE profiles SET username = 'سعد عبد الامير عبود' WHERE job_number = '103143174' AND governorate = 'babil';
UPDATE profiles SET username = 'ثائر شاكر مجيد' WHERE job_number = '103140795' AND governorate = 'babil';
UPDATE profiles SET username = 'عمار سعيد حسين' WHERE job_number = '103141602' AND governorate = 'babil';
UPDATE profiles SET username = 'قتيبة عبد الرحمن محيميد' WHERE job_number = '103143608' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد غازي حسين' WHERE job_number = '103141983' AND governorate = 'babil';
UPDATE profiles SET username = 'زيدون صادق حسن' WHERE job_number = '103140401' AND governorate = 'babil';
UPDATE profiles SET username = 'داود غني مظلوم' WHERE job_number = '103142733' AND governorate = 'babil';
UPDATE profiles SET username = 'عدوية موحان عواد' WHERE job_number = '103210311' AND governorate = 'babil';
UPDATE profiles SET username = 'زهير شريف هاشم' WHERE job_number = '103141420' AND governorate = 'babil';
UPDATE profiles SET username = 'علياء ستار وحودي' WHERE job_number = '103140670' AND governorate = 'babil';
UPDATE profiles SET username = 'بشرى مهدي صالح' WHERE job_number = '103142407' AND governorate = 'babil';
UPDATE profiles SET username = 'عقيل حمزة ناصر' WHERE job_number = '103143372' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد خضير عباس' WHERE job_number = '103141558' AND governorate = 'babil';
UPDATE profiles SET username = 'عبد الحمزة كاظم راضي' WHERE job_number = '103142788' AND governorate = 'babil';
UPDATE profiles SET username = 'مؤيد عبيس مدور' WHERE job_number = '103142845' AND governorate = 'babil';
UPDATE profiles SET username = 'حاكم حسين علي' WHERE job_number = '103144854' AND governorate = 'babil';
UPDATE profiles SET username = 'نيسان مالك عزيز' WHERE job_number = '103143343' AND governorate = 'babil';
UPDATE profiles SET username = 'فلاح حسن داخل' WHERE job_number = '106372001' AND governorate = 'babil';
UPDATE profiles SET username = 'ماهر عبد الكاظم محمد' WHERE job_number = '103222275' AND governorate = 'babil';
UPDATE profiles SET username = 'امجد ياسين خضير' WHERE job_number = '103144768' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد مبدر محسن' WHERE job_number = '103140753' AND governorate = 'babil';
UPDATE profiles SET username = 'عماد عبد الرزاق رحيم' WHERE job_number = '103140456' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب خليل إبراهيم' WHERE job_number = '103143439' AND governorate = 'babil';
UPDATE profiles SET username = 'ليث محمد كاظم' WHERE job_number = '103223070' AND governorate = 'babil';
UPDATE profiles SET username = 'صبيح خضير عبيس' WHERE job_number = '103129161' AND governorate = 'babil';
UPDATE profiles SET username = 'اعتزاز ناجي عبد الأمير' WHERE job_number = '103141136' AND governorate = 'babil';
UPDATE profiles SET username = 'عبدالمحسن جبارعبدالحسين' WHERE job_number = '103139326' AND governorate = 'babil';
UPDATE profiles SET username = 'مزهر سعيد عبد' WHERE job_number = '103209108' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن رزوقي مهدي' WHERE job_number = '103141644' AND governorate = 'babil';
UPDATE profiles SET username = 'رشا نعمة حسين' WHERE job_number = '103144416' AND governorate = 'babil';
UPDATE profiles SET username = 'مازن كريم علي' WHERE job_number = '103145493' AND governorate = 'babil';
UPDATE profiles SET username = 'ميثم هادي عبيد' WHERE job_number = '103141459' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب خليل هاشم' WHERE job_number = '103145422' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس حميد ناصر' WHERE job_number = '103142254' AND governorate = 'babil';
UPDATE profiles SET username = 'جواد كاظم فارس' WHERE job_number = '103143161' AND governorate = 'babil';
UPDATE profiles SET username = 'عقيل حسن حميد' WHERE job_number = '103144375' AND governorate = 'babil';
UPDATE profiles SET username = 'جولان اميرعبد الله' WHERE job_number = '103141165' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد حمزة عبد الله' WHERE job_number = '103140766' AND governorate = 'babil';
UPDATE profiles SET username = 'حميد علي عيسى' WHERE job_number = '103144346' AND governorate = 'babil';
UPDATE profiles SET username = 'نازك جبار حسون' WHERE job_number = '103142410' AND governorate = 'babil';
UPDATE profiles SET username = 'سلام حسام جليل' WHERE job_number = '102514678' AND governorate = 'babil';
UPDATE profiles SET username = 'حافظ حمزة عبادي' WHERE job_number = '103216728' AND governorate = 'babil';
UPDATE profiles SET username = 'ياسين كاظم عبد حسين' WHERE job_number = '103144391' AND governorate = 'babil';
UPDATE profiles SET username = 'علاء هادي هاشم' WHERE job_number = '103142999' AND governorate = 'babil';
UPDATE profiles SET username = 'سعد عبيد سلمان' WHERE job_number = '103142340' AND governorate = 'babil';
UPDATE profiles SET username = 'علي حسين شنوك' WHERE job_number = '103144544' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عباس عليوي' WHERE job_number = '103144429' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد عبد الحسين جابر' WHERE job_number = '103142478' AND governorate = 'babil';
UPDATE profiles SET username = 'فاطمة هادي كريم' WHERE job_number = '103207227' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد نوري عبد الوهاب' WHERE job_number = '103143877' AND governorate = 'babil';
UPDATE profiles SET username = 'وسام جاسم موسى' WHERE job_number = '103144432' AND governorate = 'babil';
UPDATE profiles SET username = 'ثائر صالح مزيون' WHERE job_number = '103144359' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد علي كاظم' WHERE job_number = '103144292' AND governorate = 'babil';
UPDATE profiles SET username = 'فالح خرباط عبد علي' WHERE job_number = '103142832' AND governorate = 'babil';
UPDATE profiles SET username = 'تراث جبار صاحب' WHERE job_number = '103139371' AND governorate = 'babil';
UPDATE profiles SET username = 'فارس هاني كريم' WHERE job_number = '103141110' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر محمد علي' WHERE job_number = '103140919' AND governorate = 'babil';
UPDATE profiles SET username = 'لفتة حسن جياد' WHERE job_number = '103143202' AND governorate = 'babil';
UPDATE profiles SET username = 'اسامة اياد طة' WHERE job_number = '103140104' AND governorate = 'babil';
UPDATE profiles SET username = 'لؤي حاتم عبد الحمزة' WHERE job_number = '103143794' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر محمد رضا' WHERE job_number = '103210184' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد هادي علي' WHERE job_number = '103143260' AND governorate = 'babil';
UPDATE profiles SET username = 'فارس ناصر شاكر' WHERE job_number = '103143989' AND governorate = 'babil';
UPDATE profiles SET username = 'علاء قصي احمد' WHERE job_number = '103141701' AND governorate = 'babil';
UPDATE profiles SET username = 'افتخار صالح حسن' WHERE job_number = '103139988' AND governorate = 'babil';
UPDATE profiles SET username = 'علاء عبيس كاظم' WHERE job_number = '103144940' AND governorate = 'babil';
UPDATE profiles SET username = 'بشير غانم عبد الكاظم' WHERE job_number = '103141686' AND governorate = 'babil';
UPDATE profiles SET username = 'ماجدولين فيصل غازي' WHERE job_number = '103139199' AND governorate = 'babil';
UPDATE profiles SET username = 'رياض مهدي توفيق' WHERE job_number = '103141673' AND governorate = 'babil';
UPDATE profiles SET username = 'مالك عباس علوان' WHERE job_number = '103142168' AND governorate = 'babil';
UPDATE profiles SET username = 'جعفر محان كظيم' WHERE job_number = '103143806' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب يحيى جاسم' WHERE job_number = '103208374' AND governorate = 'babil';
UPDATE profiles SET username = 'فرح اياد طه' WHERE job_number = '103139256' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر صبار عمران' WHERE job_number = '103141123' AND governorate = 'babil';
UPDATE profiles SET username = 'واثق حسين نايف' WHERE job_number = '103140852' AND governorate = 'babil';
UPDATE profiles SET username = 'اشواق فاضل سعيد' WHERE job_number = '103139920' AND governorate = 'babil';
UPDATE profiles SET username = 'رضا اسماعيل حسين' WHERE job_number = '103141107' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد نعمة جعاز' WHERE job_number = '103223137' AND governorate = 'babil';
UPDATE profiles SET username = 'موسى جواد كاظم' WHERE job_number = '103145406' AND governorate = 'babil';
UPDATE profiles SET username = 'ظافر هادي عبد' WHERE job_number = '103141660' AND governorate = 'babil';
UPDATE profiles SET username = 'هدى كريم علوان' WHERE job_number = '103141785' AND governorate = 'babil';
UPDATE profiles SET username = 'نصير عبد المهدي مجباس' WHERE job_number = '103142337' AND governorate = 'babil';
UPDATE profiles SET username = 'غانم جبر جواد' WHERE job_number = '103143091' AND governorate = 'babil';
UPDATE profiles SET username = 'رحيم جاسم كاظم' WHERE job_number = '103142618' AND governorate = 'babil';
UPDATE profiles SET username = 'رائد جبار شمخي' WHERE job_number = '103145196' AND governorate = 'babil';
UPDATE profiles SET username = 'رحمن هاشم عباس' WHERE job_number = '103141970' AND governorate = 'babil';
UPDATE profiles SET username = 'زينب محمد رضا' WHERE job_number = '103144461' AND governorate = 'babil';
UPDATE profiles SET username = 'ليلى داود سلمان' WHERE job_number = '103145167' AND governorate = 'babil';
UPDATE profiles SET username = 'دلال عمران عيسى' WHERE job_number = '103142481' AND governorate = 'babil';
UPDATE profiles SET username = 'جاسم محمد هاشم' WHERE job_number = '103140050' AND governorate = 'babil';
UPDATE profiles SET username = 'نضال محمد حسن' WHERE job_number = '103142283' AND governorate = 'babil';
UPDATE profiles SET username = 'ضحى ماجد رشيد' WHERE job_number = '103140373' AND governorate = 'babil';
UPDATE profiles SET username = 'وسام حمد حمزة' WHERE job_number = '103143835' AND governorate = 'babil';
UPDATE profiles SET username = 'اخلاص فاضل مهدي' WHERE job_number = '103140740' AND governorate = 'babil';
UPDATE profiles SET username = 'ميثم جبار كريم' WHERE job_number = '103140146' AND governorate = 'babil';
UPDATE profiles SET username = 'بشرى حمادي حسن' WHERE job_number = '103139623' AND governorate = 'babil';
UPDATE profiles SET username = 'عايد كاظم عبد العباس' WHERE job_number = '103140089' AND governorate = 'babil';
UPDATE profiles SET username = 'بدور علي حسين' WHERE job_number = '103142353' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس نجم عبود' WHERE job_number = '103140133' AND governorate = 'babil';
UPDATE profiles SET username = 'عدوية عبد زويد' WHERE job_number = '103143710' AND governorate = 'babil';
UPDATE profiles SET username = 'سامي نفل حمد' WHERE job_number = '103141909' AND governorate = 'babil';
UPDATE profiles SET username = 'خالد محمد علوان' WHERE job_number = '103140188' AND governorate = 'babil';
UPDATE profiles SET username = 'ثامر مرزة سلطان' WHERE job_number = '103143455' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدرعبد الجبارعبد العباس' WHERE job_number = '103144630' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن كطوف عبيس' WHERE job_number = '103145039' AND governorate = 'babil';
UPDATE profiles SET username = 'علاء حسين كريم' WHERE job_number = '103141657' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر حسن عبد عباس' WHERE job_number = '103144320' AND governorate = 'babil';
UPDATE profiles SET username = 'مصطفى عبد الكريم كاظم' WHERE job_number = '103144599' AND governorate = 'babil';
UPDATE profiles SET username = 'عمارعبد الجبارعبد العباس' WHERE job_number = '103144627' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عبد الحسين عبد الله' WHERE job_number = '103144995' AND governorate = 'babil';
UPDATE profiles SET username = 'احسان علي حسين' WHERE job_number = '103144742' AND governorate = 'babil';
UPDATE profiles SET username = 'وسام صالح عبيد' WHERE job_number = '103140258' AND governorate = 'babil';
UPDATE profiles SET username = 'صبيح وحيد موسى' WHERE job_number = '103206310' AND governorate = 'babil';
UPDATE profiles SET username = 'هيثم صبر حسين' WHERE job_number = '103144234' AND governorate = 'babil';
UPDATE profiles SET username = 'بشير ابراهيم حنتوش' WHERE job_number = '103142692' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين محمد علي' WHERE job_number = '103210270' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر بدر كاظم' WHERE job_number = '103140191' AND governorate = 'babil';
UPDATE profiles SET username = 'وسام محمد طالب' WHERE job_number = '103144867' AND governorate = 'babil';
UPDATE profiles SET username = 'عقيل شاكر عناد' WHERE job_number = '103145211' AND governorate = 'babil';
UPDATE profiles SET username = 'عقيل عبد كريم' WHERE job_number = '103145208' AND governorate = 'babil';
UPDATE profiles SET username = 'كامل سايب متعب' WHERE job_number = '103145109' AND governorate = 'babil';
UPDATE profiles SET username = 'بشار فليح حسن' WHERE job_number = '103145068' AND governorate = 'babil';
UPDATE profiles SET username = 'مهند علي عبود' WHERE job_number = '103144276' AND governorate = 'babil';
UPDATE profiles SET username = 'هشام هاني محمد' WHERE job_number = '103145589' AND governorate = 'babil';
UPDATE profiles SET username = 'ناهض عادي رباط' WHERE job_number = '103143228' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عادل هادي' WHERE job_number = '103144289' AND governorate = 'babil';
UPDATE profiles SET username = 'لينا حسين ناهي' WHERE job_number = '103141714' AND governorate = 'babil';
UPDATE profiles SET username = 'قيود خزعل عطشان' WHERE job_number = '103140047' AND governorate = 'babil';
UPDATE profiles SET username = 'هند سالم محيسن' WHERE job_number = '103144487' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن حسين حمزة' WHERE job_number = '103144656' AND governorate = 'babil';
UPDATE profiles SET username = 'فارس زبير عبيس' WHERE job_number = '103145071' AND governorate = 'babil';
UPDATE profiles SET username = 'امير سعدي عبد الأمير' WHERE job_number = '103145534' AND governorate = 'babil';
UPDATE profiles SET username = 'نظام سعد عبد الرضا' WHERE job_number = '103145125' AND governorate = 'babil';
UPDATE profiles SET username = 'عدي جعفر ناجي' WHERE job_number = '103144081' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد جابر تايه' WHERE job_number = '103144164' AND governorate = 'babil';
UPDATE profiles SET username = 'حنان خلف مطر' WHERE job_number = '103144333' AND governorate = 'babil';
UPDATE profiles SET username = 'علي فائق رزيج' WHERE job_number = '103144685' AND governorate = 'babil';
UPDATE profiles SET username = 'ليلى مرزه حرش' WHERE job_number = '103216856' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر نعمة مظلوم' WHERE job_number = '103144263' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين علاوي جاسم' WHERE job_number = '103144177' AND governorate = 'babil';
UPDATE profiles SET username = 'سعد محسن صكب' WHERE job_number = '103140162' AND governorate = 'babil';
UPDATE profiles SET username = 'باسم عدنان جاسم' WHERE job_number = '103144528' AND governorate = 'babil';
UPDATE profiles SET username = 'حامد حسين عبد' WHERE job_number = '103140216' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر جبار كاظم' WHERE job_number = '103144065' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد حمزة مهدي' WHERE job_number = '103143695' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عباس جليل' WHERE job_number = '103145604' AND governorate = 'babil';
UPDATE profiles SET username = 'سرور سعد داود' WHERE job_number = '103207214' AND governorate = 'babil';
UPDATE profiles SET username = 'بسام اسماعيل جواد' WHERE job_number = '103144180' AND governorate = 'babil';
UPDATE profiles SET username = 'بشير علي حسن' WHERE job_number = '103143004' AND governorate = 'babil';
UPDATE profiles SET username = 'ختام عباس حسون' WHERE job_number = '103143033' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد جياد سرحان' WHERE job_number = '103144205' AND governorate = 'babil';
UPDATE profiles SET username = 'عدي داود صليبي' WHERE job_number = '106371772' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر علي حبيب' WHERE job_number = '103144193' AND governorate = 'babil';
UPDATE profiles SET username = 'عماد عبد الكاظم شكر' WHERE job_number = '103140232' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عبد الله سلمان' WHERE job_number = '103145646' AND governorate = 'babil';
UPDATE profiles SET username = 'سناء ناطق خضير' WHERE job_number = '103143976' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد حسن محمد' WHERE job_number = '103144982' AND governorate = 'babil';
UPDATE profiles SET username = 'اثير ياسين خضير' WHERE job_number = '103144573' AND governorate = 'babil';
UPDATE profiles SET username = 'مقدام كاظم محمود' WHERE job_number = '103142621' AND governorate = 'babil';
UPDATE profiles SET username = 'صادق والي عطوان' WHERE job_number = '103144119' AND governorate = 'babil';
UPDATE profiles SET username = 'مهدي علي حسين' WHERE job_number = '103144151' AND governorate = 'babil';
UPDATE profiles SET username = 'حافظ مخيلف عطية' WHERE job_number = '103144036' AND governorate = 'babil';
UPDATE profiles SET username = 'فاضل علي عبيد' WHERE job_number = '103144247' AND governorate = 'babil';
UPDATE profiles SET username = 'امين علي محمد' WHERE job_number = '103141868' AND governorate = 'babil';
UPDATE profiles SET username = 'فراس فلاح  مالك' WHERE job_number = '103140021' AND governorate = 'babil';
UPDATE profiles SET username = 'باسم طالب حسن' WHERE job_number = '103144052' AND governorate = 'babil';
UPDATE profiles SET username = 'سماء ماجد حميد' WHERE job_number = '103215556' AND governorate = 'babil';
UPDATE profiles SET username = 'اسيل عبدالعال جبر' WHERE job_number = '102514636' AND governorate = 'babil';
UPDATE profiles SET username = 'وصال طالب عبد حسون' WHERE job_number = '103216773' AND governorate = 'babil';
UPDATE profiles SET username = 'رشا مظهر حبيب' WHERE job_number = '103216827' AND governorate = 'babil';
UPDATE profiles SET username = 'اكرم شعبان حوران' WHERE job_number = '103216603' AND governorate = 'babil';
UPDATE profiles SET username = 'هاني عيسى مهدي' WHERE job_number = '103142720' AND governorate = 'babil';
UPDATE profiles SET username = 'ابراهيم حبيب جاسم' WHERE job_number = '103144304' AND governorate = 'babil';
UPDATE profiles SET username = 'رافد علي كاظم' WHERE job_number = '103144317' AND governorate = 'babil';
UPDATE profiles SET username = 'عدنان كاظم حسين' WHERE job_number = '103144614' AND governorate = 'babil';
UPDATE profiles SET username = 'عدي عبيد حسن' WHERE job_number = '103221780' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر محمد عبد الحمزة' WHERE job_number = '103144122' AND governorate = 'babil';
UPDATE profiles SET username = 'علي حمزة ياسر' WHERE job_number = '103144560' AND governorate = 'babil';
UPDATE profiles SET username = 'محمود حمزة هاني' WHERE job_number = '103144700' AND governorate = 'babil';
UPDATE profiles SET username = 'مهدي وناس راشد' WHERE job_number = '103144362' AND governorate = 'babil';
UPDATE profiles SET username = 'امير كاظم حسن' WHERE job_number = '103144713' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد فليح جاسم' WHERE job_number = '103144094' AND governorate = 'babil';
UPDATE profiles SET username = 'رضا اسماعيل خضير' WHERE job_number = '103145435' AND governorate = 'babil';
UPDATE profiles SET username = 'امير حيدر عبد علي' WHERE job_number = '103144078' AND governorate = 'babil';
UPDATE profiles SET username = 'زيد يحيى نايف' WHERE job_number = '103141251' AND governorate = 'babil';
UPDATE profiles SET username = 'فضيلة خضير عباس' WHERE job_number = '103156804' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين هادي جميل' WHERE job_number = '103144221' AND governorate = 'babil';
UPDATE profiles SET username = 'سارة علي محسن' WHERE job_number = '103144726' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عبد الحسين جلاب' WHERE job_number = '103145055' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد هادي جميل' WHERE job_number = '103144250' AND governorate = 'babil';
UPDATE profiles SET username = 'مؤيد عباس سلطان' WHERE job_number = '103140229' AND governorate = 'babil';
UPDATE profiles SET username = 'اسامة عامر عبد الأمير' WHERE job_number = '103144010' AND governorate = 'babil';
UPDATE profiles SET username = 'يونس عبود عبد الرضا' WHERE job_number = '103144106' AND governorate = 'babil';
UPDATE profiles SET username = 'عايد ناهي حسن' WHERE job_number = '103145084' AND governorate = 'babil';
UPDATE profiles SET username = 'حافظ مجيد حميد' WHERE job_number = '103144643' AND governorate = 'babil';
UPDATE profiles SET username = 'عطاء ثامر جواد' WHERE job_number = '103216489' AND governorate = 'babil';
UPDATE profiles SET username = 'محسن عبيس محيسن' WHERE job_number = '103216559' AND governorate = 'babil';
UPDATE profiles SET username = 'لما فلاح نصر' WHERE job_number = '102514694' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد عايد عبادة' WHERE job_number = '103216632' AND governorate = 'babil';
UPDATE profiles SET username = 'عماد عبيد بليبل' WHERE job_number = '103216629' AND governorate = 'babil';
UPDATE profiles SET username = 'حسام عبود حسين' WHERE job_number = '103216207' AND governorate = 'babil';
UPDATE profiles SET username = 'محمود سعيد محمود' WHERE job_number = '103145295' AND governorate = 'babil';
UPDATE profiles SET username = 'بهاء غانم عمشان' WHERE job_number = '103144908' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين جبر موسى' WHERE job_number = '103144771' AND governorate = 'babil';
UPDATE profiles SET username = 'وسام هاشم حسين' WHERE job_number = '103144669' AND governorate = 'babil';
UPDATE profiles SET username = 'نضال هادي مصطفى' WHERE job_number = '103212870' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد سليم حياوي' WHERE job_number = '103144937' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر شهيد كاظم' WHERE job_number = '103216731' AND governorate = 'babil';
UPDATE profiles SET username = 'لبنى محسن عبد الحسين' WHERE job_number = '103216504' AND governorate = 'babil';
UPDATE profiles SET username = 'غزوان فلاح محسن' WHERE job_number = '103216799' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر مهدي حسن' WHERE job_number = '103216179' AND governorate = 'babil';
UPDATE profiles SET username = 'نصير يونس عبيد' WHERE job_number = '103144148' AND governorate = 'babil';
UPDATE profiles SET username = 'نور فؤاد مهدي' WHERE job_number = '103216760' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن خليل إبراهيم' WHERE job_number = '103215501' AND governorate = 'babil';
UPDATE profiles SET username = 'مهند شهيد شاكر' WHERE job_number = '102514706' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر كريم محمد' WHERE job_number = '103145365' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد محمد حامد' WHERE job_number = '103140302' AND governorate = 'babil';
UPDATE profiles SET username = 'نوفل كطران مزاحم' WHERE job_number = '103143819' AND governorate = 'babil';
UPDATE profiles SET username = 'وليد ابراهيم حسين' WHERE job_number = '103143752' AND governorate = 'babil';
UPDATE profiles SET username = 'نبيل مظلوم ربيط' WHERE job_number = '103140878' AND governorate = 'babil';
UPDATE profiles SET username = 'هناء فاهم كناوي' WHERE job_number = '103143129' AND governorate = 'babil';
UPDATE profiles SET username = 'سلوى عبد الأمير طالب' WHERE job_number = '103140287' AND governorate = 'babil';
UPDATE profiles SET username = 'ناهدة خليل إبراهيم' WHERE job_number = '103220675' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين محسن عباس' WHERE job_number = '103142142' AND governorate = 'babil';
UPDATE profiles SET username = 'حبيب شتيوي حسن' WHERE job_number = '103143145' AND governorate = 'babil';
UPDATE profiles SET username = 'خالد احمد حمزة' WHERE job_number = '103143020' AND governorate = 'babil';
UPDATE profiles SET username = 'نصير حسين مرزة' WHERE job_number = '103143682' AND governorate = 'babil';
UPDATE profiles SET username = 'مشتاق طالب عبد الله' WHERE job_number = '103220691' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر علي ظاهر' WHERE job_number = '103140881' AND governorate = 'babil';
UPDATE profiles SET username = 'صادق هادي جبر' WHERE job_number = '103207199' AND governorate = 'babil';
UPDATE profiles SET username = 'منعم جبار خضير' WHERE job_number = '103142861' AND governorate = 'babil';
UPDATE profiles SET username = 'حامد تومان عاجل' WHERE job_number = '103142874' AND governorate = 'babil';
UPDATE profiles SET username = 'هادي عدنان حسن' WHERE job_number = '103149677' AND governorate = 'babil';
UPDATE profiles SET username = 'فاضل عبد علي ديكان' WHERE job_number = '103143950' AND governorate = 'babil';
UPDATE profiles SET username = 'صفاء حمزة ازناد' WHERE job_number = '103215444' AND governorate = 'babil';
UPDATE profiles SET username = 'علي طالب فالح' WHERE job_number = '103216843' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد عبد حمزة' WHERE job_number = '103216830' AND governorate = 'babil';
UPDATE profiles SET username = 'صباح سامي شنو' WHERE job_number = '103218245' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد خضير عباس' WHERE job_number = '103216744' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر عباس مدب' WHERE job_number = '103145170' AND governorate = 'babil';
UPDATE profiles SET username = 'كفاح جفات شمران' WHERE job_number = '103216517' AND governorate = 'babil';
UPDATE profiles SET username = 'علي مهدي غزوان' WHERE job_number = '103144953' AND governorate = 'babil';
UPDATE profiles SET username = 'زيد علي عبد الحسين' WHERE job_number = '103216814' AND governorate = 'babil';
UPDATE profiles SET username = 'مشتاق طالب حسن' WHERE job_number = '103223450' AND governorate = 'babil';
UPDATE profiles SET username = 'حسنين سلام عيسى' WHERE job_number = '103216520' AND governorate = 'babil';
UPDATE profiles SET username = 'صفا محمد عبد هادي' WHERE job_number = '103216492' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد حسين عليوي' WHERE job_number = '103144755' AND governorate = 'babil';
UPDATE profiles SET username = 'عماد سرتيل عبيد' WHERE job_number = '103145224' AND governorate = 'babil';
UPDATE profiles SET username = 'ربيع محمود هاشم' WHERE job_number = '103156552' AND governorate = 'babil';
UPDATE profiles SET username = 'عصام علي كاظم' WHERE job_number = '103208527' AND governorate = 'babil';
UPDATE profiles SET username = 'شيماء مكي إبراهيم' WHERE job_number = '102484540' AND governorate = 'babil';
UPDATE profiles SET username = 'علي هاشم كاظم' WHERE job_number = '103216645' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين صالح جاسم' WHERE job_number = '103225584' AND governorate = 'babil';
UPDATE profiles SET username = 'حسنين حمزة علي' WHERE job_number = '103145336' AND governorate = 'babil';
UPDATE profiles SET username = 'حبيب حاتم مزهر' WHERE job_number = '103145183' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر حسين جواد' WHERE job_number = '103210241' AND governorate = 'babil';
UPDATE profiles SET username = 'سلام عبد السادة حمزة' WHERE job_number = '103145563' AND governorate = 'babil';
UPDATE profiles SET username = 'غيث اخاء مجيد' WHERE job_number = '103209926' AND governorate = 'babil';
UPDATE profiles SET username = 'علي كامل عبد الرحيم' WHERE job_number = '103207243' AND governorate = 'babil';
UPDATE profiles SET username = 'نوار موفق جواد' WHERE job_number = '103207326' AND governorate = 'babil';
UPDATE profiles SET username = 'هالة حسام محمد' WHERE job_number = '103216757' AND governorate = 'babil';
UPDATE profiles SET username = 'خليل جاسم هاشم' WHERE job_number = '103145237' AND governorate = 'babil';
UPDATE profiles SET username = 'صفاء سدخان حمزة' WHERE job_number = '103145279' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد عبد الرزاق عباس' WHERE job_number = '103145253' AND governorate = 'babil';
UPDATE profiles SET username = 'عامر حامد نعمة' WHERE job_number = '103145240' AND governorate = 'babil';
UPDATE profiles SET username = 'باسم سلمان حسن' WHERE job_number = '103145042' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن عبد العالي حسن' WHERE job_number = '103145310' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين علي سرحان' WHERE job_number = '103145378' AND governorate = 'babil';
UPDATE profiles SET username = 'وسام عبود حسين' WHERE job_number = '103145307' AND governorate = 'babil';
UPDATE profiles SET username = 'ضياء سلمان حميد' WHERE job_number = '103183170' AND governorate = 'babil';
UPDATE profiles SET username = 'صلاح خضير عبيس' WHERE job_number = '103144911' AND governorate = 'babil';
UPDATE profiles SET username = 'خالد عبد علي نعمة' WHERE job_number = '103145266' AND governorate = 'babil';
UPDATE profiles SET username = 'جواد عبد الكاظم حمزة' WHERE job_number = '103143103' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن حامد موسى' WHERE job_number = '103144924' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن نوري عباس' WHERE job_number = '103141798' AND governorate = 'babil';
UPDATE profiles SET username = 'فاتن جابر كاظم' WHERE job_number = '155191150' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد عيسى فرحان' WHERE job_number = '103222288' AND governorate = 'babil';
UPDATE profiles SET username = 'مهند علي ذباح' WHERE job_number = '103144531' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد نادر محمد' WHERE job_number = '103207780' AND governorate = 'babil';
UPDATE profiles SET username = 'منهل محمد عبد الحمزة' WHERE job_number = '103145381' AND governorate = 'babil';
UPDATE profiles SET username = 'امجد جاسم علي' WHERE job_number = '103221777' AND governorate = 'babil';
UPDATE profiles SET username = 'سامي عبد النبي كاظم' WHERE job_number = '102496165' AND governorate = 'babil';
UPDATE profiles SET username = 'محمد عبد الرحمن داود' WHERE job_number = '103145349' AND governorate = 'babil';
UPDATE profiles SET username = 'خضير كتاب حباوي' WHERE job_number = '103210225' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد نبيل مزهر' WHERE job_number = '103145141' AND governorate = 'babil';
UPDATE profiles SET username = 'محسن ثامر محسن' WHERE job_number = '150896218' AND governorate = 'babil';
UPDATE profiles SET username = 'علي عبد الخالق علي' WHERE job_number = '103216801' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر عبد الكريم كاظم' WHERE job_number = '150975546' AND governorate = 'babil';
UPDATE profiles SET username = 'اثير عبد المهدي ابريهي' WHERE job_number = '150896292' AND governorate = 'babil';
UPDATE profiles SET username = 'كاظم علي عبيد' WHERE job_number = '103216616' AND governorate = 'babil';
UPDATE profiles SET username = 'علاء غانم عمشان' WHERE job_number = '103216319' AND governorate = 'babil';
UPDATE profiles SET username = 'مريم عجاج عايد' WHERE job_number = '103218737' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر كريم مظهر' WHERE job_number = '150896359' AND governorate = 'babil';
UPDATE profiles SET username = 'اسراء سعد عبد كاظم' WHERE job_number = '148954180' AND governorate = 'babil';
UPDATE profiles SET username = 'عبد الامير بخيت عباس' WHERE job_number = '103144515' AND governorate = 'babil';
UPDATE profiles SET username = 'عباس محمد حمزة' WHERE job_number = '103145592' AND governorate = 'babil';
UPDATE profiles SET username = 'غانم زبير عبيس' WHERE job_number = '103216533' AND governorate = 'babil';
UPDATE profiles SET username = 'قصي سداوي حمزة' WHERE job_number = '102496251' AND governorate = 'babil';
UPDATE profiles SET username = 'صلاح هادي عبود' WHERE job_number = '103215428' AND governorate = 'babil';
UPDATE profiles SET username = 'شهد عبد الكريم عبد الباقر' WHERE job_number = '148954193' AND governorate = 'babil';
UPDATE profiles SET username = 'امال عبد الزهرة وناس' WHERE job_number = '148954164' AND governorate = 'babil';
UPDATE profiles SET username = 'سيف سعد داود' WHERE job_number = '148954205' AND governorate = 'babil';
UPDATE profiles SET username = 'ايلاف صلاح حسن' WHERE job_number = '148954218' AND governorate = 'babil';
UPDATE profiles SET username = 'ميقات حسن علي' WHERE job_number = '143138929' AND governorate = 'babil';
UPDATE profiles SET username = 'حسن علي جبر' WHERE job_number = '148954177' AND governorate = 'babil';
UPDATE profiles SET username = 'حسام حيدر صلاح' WHERE job_number = '151116595' AND governorate = 'babil';
UPDATE profiles SET username = 'احمد علي عبيد' WHERE job_number = '103222262' AND governorate = 'babil';
UPDATE profiles SET username = 'تهاني عبد الامير احمد' WHERE job_number = '156481526' AND governorate = 'babil';
UPDATE profiles SET username = 'كرار طالب عبدالله' WHERE job_number = '103216223' AND governorate = 'babil';
UPDATE profiles SET username = 'وديان كريم علي' WHERE job_number = '151116537' AND governorate = 'babil';
UPDATE profiles SET username = 'علي حميد كاظم' WHERE job_number = '103216265' AND governorate = 'babil';
UPDATE profiles SET username = 'نهاد عبد لفته' WHERE job_number = '103223926' AND governorate = 'babil';
UPDATE profiles SET username = 'ثناء عباس حمزة' WHERE job_number = '153979727' AND governorate = 'babil';
UPDATE profiles SET username = 'هدى جبار حسون' WHERE job_number = '151116540' AND governorate = 'babil';
UPDATE profiles SET username = 'نعيمة جواد صالح' WHERE job_number = '103223942' AND governorate = 'babil';
UPDATE profiles SET username = 'مروان باسم مجيد' WHERE job_number = '102508949' AND governorate = 'babil';
UPDATE profiles SET username = 'علي تركي عكموش' WHERE job_number = '103223955' AND governorate = 'babil';
UPDATE profiles SET username = 'نسرين كريم جسام' WHERE job_number = '103223900' AND governorate = 'babil';
UPDATE profiles SET username = 'فلاح مهدي عبدالزهرة' WHERE job_number = '102493195' AND governorate = 'babil';
UPDATE profiles SET username = 'حسين صكر عبد خلف' WHERE job_number = '103223939' AND governorate = 'babil';
UPDATE profiles SET username = 'امل احمد سويدان' WHERE job_number = '103139339' AND governorate = 'babil';
UPDATE profiles SET username = 'حيدر عبد العباس اسود' WHERE job_number = '103141040' AND governorate = 'babil';
UPDATE profiles SET username = 'كاظم محسن مدلول' WHERE job_number = '103144023' AND governorate = 'babil';