#!/bin/bash
echo "=== work_locations count ==="
docker exec -i supabase-db psql -U postgres -t -A -c "SELECT count(*) FROM work_locations;"
echo "=== columns (name, nullable, default) ==="
docker exec -i supabase-db psql -U postgres -t -A -c "SELECT column_name, is_nullable, column_default FROM information_schema.columns WHERE table_name='work_locations' ORDER BY ordinal_position;"
echo "=== FK constraints on work_locations ==="
docker exec -i supabase-db psql -U postgres -t -A -c "SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='work_locations'::regclass AND contype='f';"
echo "=== current names ==="
docker exec -i supabase-db psql -U postgres -t -A -c "SELECT id, name, is_active FROM work_locations ORDER BY name;"
echo "=== admin candidates babil ==="
docker exec -i supabase-db psql -U postgres -t -A -c "SELECT id, full_name, admin_role FROM profiles WHERE governorate='babil' AND admin_role IN ('general','developer','it_supervisor') ORDER BY created_at LIMIT 3;"
echo "=== admin candidates najaf ==="
docker exec -i supabase-db psql -U postgres -t -A -c "SELECT id, full_name, admin_role FROM profiles WHERE governorate='najaf' AND admin_role IN ('general','developer','it_supervisor') ORDER BY created_at LIMIT 3;"
echo "=== helper functions exist ==="
docker exec -i supabase-db psql -U postgres -t -A -c "SELECT proname FROM pg_proc WHERE proname IN ('get_my_governorate','is_admin');"
